os:
- linux
addons:
  ssh_known_hosts:
  - insultr.westeurope.cloudapp.azure.com
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- 7.0
install:
- composer install
script:
- vendor/bin/phpunit --configuration phpunit.xml --coverage-text
deploy:
- provider: script
  skip_cleanup: true
  script:
  - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $DEPLOY_USER@$DEPLOY_HOST:/home/johan/insultr
  on:
    branch: master
notifications:
  email:
    recipients: johan.holmberg@mah.se
before_deploy:
- openssl aes-256-cbc -K $encrypted_fd2bea8427ff_key -iv $encrypted_fd2bea8427ff_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
